### ISSUE TITLE
Could the "rg" part have the data of "intercept"? If it can be calculated, how do I make it?

### ISSUE THREAD

**Issue by MikeKiki101** [mglev1n/ldscr#11]

**Comment by mglev1n** [comment]
Do you have a particular use-case in mind for the cross-trait intercept?

**Comment by MikeKiki101** [comment]
> Do you have a particular use-case in mind for the cross-trait intercept?

I just want to use it for CC-GWAS analysis which needs cross trait intercept.

**Comment by mglev1n** [comment]
I think `covariance_res$intercept` which is created as part of the following line may represent the cross-trait intercept, but I'll need to do some comparisons with the original LDSC python package to double-check. https://github.com/mglev1n/ldscr/blob/7c8e1387bdd4f8f9dbc6f92a40e09d624b201b33/R/ldsc_rg.R#L262

Most of this package just implements the ldsc code from the `GenomicSEM` package (https://github.com/GenomicSEM/GenomicSEM) with a friendlier user-interface - I don't think they originally exposed the cross-trait intercept, which is why it will take a little investigation.

**Comment by MikeKiki101** [comment]
> I think `covariance_res$intercept` which is created as part of the following line may represent the cross-trait intercept, but I'll need to do some comparisons with the original LDSC python package to double-check. https://github.com/mglev1n/ldscr/blob/7c8e1387bdd4f8f9dbc6f92a40e09d624b201b33/R/ldsc_rg.R#L262
> 
> Most of this package just implements the ldsc code from the `GenomicSEM` package (https://github.com/GenomicSEM/GenomicSEM) with a friendlier user-interface - I don't think they originally exposed the cross-trait intercept, which is why it will take a little investigation.

OK, thank you very much！I will figure it out！
