### ISSUE TITLE
I am unable to install using commands

### ISSUE THREAD

**Issue by SetSailAHMU** [mglev1n/ldscr#4]
> devtools::install_github("mglev1n/ldscr")
Downloading GitHub repo mglev1n/ldscr@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
 download from 'https://api.github.com/repos/mglev1n/ldscr/tarball/HEAD' failed
Thank you for building the package
but When I tried to install, this error occurred

**Comment by liusl9727** [comment]
Hi, 
I've met the same problem. You can directly download this package from 'https://api.github.com/repos/mglev1n/ldscr/tarball/' and install it locally. I think this will work.

**Comment by SetSailAHMU** [comment]
> Hi, I've met the same problem. You can directly download this package from 'https://api.github.com/repos/mglev1n/ldscr/tarball/' and install it locally. I think this will work.

Thank you for your kind advice💕💕💕, but when I put the downloaded file into C:\Users\steams\AppData\Local\R\win-library\4.3 and renamed it "ldscr" to try to use it

library(ldscr)

'ldscr' is not a valid installed package

This error occurs and confused me

**Comment by mglev1n** [comment]
I've tried to replicate this issue on both mac and linux machines, without success. I'm currently re-running package tests on GitHub Actions, which includes Windows/Mac/Linux, to see if that raises an issues. The package is relatively large (~200MB) because it includes LD score files - I wonder if you're running into timeout issues from the `utils::download.file()` call in `devtools::install_github()`. A couple things to try:

- Increase the `download.file()` timeout by running: `options(timeout=360)`
- Try using the `pak` package to install (eg. `pak::pak("mglev1n/ldscr")`)
