### ISSUE TITLE
how can i transfer the format into the input like your example?

### ISSUE THREAD

**Issue by pubTools** [mglev1n/ldscr#6]
thanks for your excellent job!

for example:
from
![248afb2be678117588ac7fd452b2dfc](https://github.com/mglev1n/ldscr/assets/39917104/1d7d602a-f012-47f7-8e2c-bf1e166180cc)
to
![eb834c42f8ef8f52e3a84ca6bee7970](https://github.com/mglev1n/ldscr/assets/39917104/d70cbcb0-db70-455c-832a-beaa3d14bff0)

**Comment by mglev1n** [comment]
There are several tools to transform your summary statistics into the "munged" format required by the ldsc tools. Some examples include:
- `munge_sumstats.py` (original python script provided by the `ldsc` authors): https://github.com/bulik/ldsc
- `MungeSumstats` (package for R): https://neurogenomics.github.io/MungeSumstats/articles/MungeSumstats.html
- `munge` (function from the GenomicSEM R package): https://github.com/GenomicSEM/GenomicSEM

**Comment by fangzhoufan** [comment]
If I have a GWAS dataframe which includes A1 A2 SNP N FRE and so on, could I use the math (Z=beta/sebeta) to calulate the Z, instead of using the  MungeSumstats packages ? That correct ?

**Comment by mglev1n** [comment]
Mathematically that calculation of Z-score is correct. However, because the Z-scores are signed, you'll want to ensure your alleles correspond to those used in the reference file (and the sign of the Z-score is adjusted accordingly. The munge functions referenced above perform several checks of the data (see: https://github.com/GenomicSEM/GenomicSEM/blob/master/R/munge_main.R), and using them is _strongly_ encouraged.
